name: avilas_manager_app
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_messaging: ^7.0.3
  badges: ^1.1.6
  carousel_slider: ^2.3.1
  flutter_dotenv: ^3.1.0
  http: ^0.12.2
  flutter_secure_storage: ^3.3.5
  flushbar: ^1.10.4
  json_annotation: ^3.1.1
  pull_to_refresh: ^1.6.3
  infinite_scroll_pagination: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1
  build_runner: ^1.10.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
